name: validate-json
on:
  push:
  pull_request:
jobs:
  validate:
    name: check validate json files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: validate json files
        run: |
          cat $(npx valid-json-cli ./test.json)
          cat $(npx valid-json-cli ./error.json)